name: todo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Value equality
  equatable: ^2.0.3
  # Apple' icons
  cupertino_icons: ^1.0.2
  # Bloc for state management
  flutter_bloc: ^8.0.0
  # Get db path or another path
  path: ^1.8.0
  # Store persistence data
  sqflite: ^2.0.2
  # Functional programming thingies
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mock classes
  mocktail: ^0.3.0
  # make unit testing in bloc easier
  bloc_test: ^9.0.3
  # default lib
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


